/**
 * FishSpecies - Complete fish species database (60+ species).
 * No imports. Pure data module.
 * Exports: FISH_SPECIES array, getFishByName(), getFishForBiome(), getFishByRarity().
 *
 * Each species: name, scientificName, weightMin, weightMax (kg), fightRating (1-10),
 * habitat (lake/river/ocean/swamp), depthPreference (shallow/mid/deep),
 * biomes [], timePreference (day/dawn/dusk/night/any), weatherPreference (clear/rain/storm/any),
 * lurePreference [], rarity (common/uncommon/rare/legendary), flavorText, basePrice.
 */

export const FISH_SPECIES = [
  // === COMMON FRESHWATER ===
  { name: 'Largemouth Bass', scientificName: 'Micropterus salmoides', weightMin: 0.5, weightMax: 5.0, fightRating: 4, habitat: 'lake', depthPreference: 'shallow', biomes: ['plains', 'forest', 'wetlands'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['spinner', 'worm', 'crankbait'], rarity: 'common', flavorText: 'The king of freshwater sport fishing. Aggressive and widespread.', basePrice: 8 },
  { name: 'Smallmouth Bass', scientificName: 'Micropterus dolomieu', weightMin: 0.3, weightMax: 3.5, fightRating: 5, habitat: 'river', depthPreference: 'mid', biomes: ['plains', 'forest', 'mountain'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['spinner', 'jig', 'crankbait'], rarity: 'common', flavorText: 'Pound for pound, one of the hardest fighters in freshwater.', basePrice: 10 },
  { name: 'Yellow Perch', scientificName: 'Perca flavescens', weightMin: 0.1, weightMax: 1.0, fightRating: 2, habitat: 'lake', depthPreference: 'shallow', biomes: ['plains', 'forest', 'wetlands'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['worm', 'minnow', 'jig'], rarity: 'common', flavorText: 'A staple panfish, excellent eating for those who catch enough.', basePrice: 4 },
  { name: 'Rainbow Trout', scientificName: 'Oncorhynchus mykiss', weightMin: 0.3, weightMax: 4.0, fightRating: 5, habitat: 'river', depthPreference: 'mid', biomes: ['mountain', 'forest'], timePreference: 'dawn', weatherPreference: 'clear', lurePreference: ['fly', 'spinner', 'worm'], rarity: 'common', flavorText: 'Prized for its acrobatic leaps and vibrant coloring.', basePrice: 12 },
  { name: 'Brown Trout', scientificName: 'Salmo trutta', weightMin: 0.4, weightMax: 5.0, fightRating: 5, habitat: 'river', depthPreference: 'mid', biomes: ['mountain', 'forest', 'tundra'], timePreference: 'dusk', weatherPreference: 'rain', lurePreference: ['fly', 'spinner', 'minnow'], rarity: 'common', flavorText: 'A wary and intelligent fish that challenges even experienced anglers.', basePrice: 14 },
  { name: 'Common Carp', scientificName: 'Cyprinus carpio', weightMin: 1.0, weightMax: 15.0, fightRating: 6, habitat: 'lake', depthPreference: 'deep', biomes: ['plains', 'wetlands', 'forest'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['corn', 'dough', 'worm'], rarity: 'common', flavorText: 'An ancient fish, revered in some cultures and scorned in others.', basePrice: 6 },
  { name: 'Northern Pike', scientificName: 'Esox lucius', weightMin: 1.0, weightMax: 12.0, fightRating: 7, habitat: 'lake', depthPreference: 'shallow', biomes: ['plains', 'forest', 'wetlands', 'tundra'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['spoon', 'crankbait', 'minnow'], rarity: 'common', flavorText: 'The water wolf. An ambush predator with razor-sharp teeth.', basePrice: 10 },
  { name: 'Atlantic Salmon', scientificName: 'Salmo salar', weightMin: 2.0, weightMax: 12.0, fightRating: 7, habitat: 'river', depthPreference: 'mid', biomes: ['mountain', 'forest', 'tundra'], timePreference: 'dawn', weatherPreference: 'rain', lurePreference: ['fly', 'spinner', 'spoon'], rarity: 'common', flavorText: 'The leaper. Returns from the sea to spawn in the rivers of its birth.', basePrice: 18 },
  { name: 'Channel Catfish', scientificName: 'Ictalurus punctatus', weightMin: 0.5, weightMax: 10.0, fightRating: 4, habitat: 'lake', depthPreference: 'deep', biomes: ['plains', 'wetlands', 'forest'], timePreference: 'night', weatherPreference: 'any', lurePreference: ['stinkbait', 'worm', 'chicken'], rarity: 'common', flavorText: 'A bottom feeder with an excellent sense of smell and taste.', basePrice: 7 },
  { name: 'Bluegill', scientificName: 'Lepomis macrochirus', weightMin: 0.05, weightMax: 0.5, fightRating: 1, habitat: 'lake', depthPreference: 'shallow', biomes: ['plains', 'forest', 'wetlands'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['worm', 'cricket', 'fly'], rarity: 'common', flavorText: 'The first fish many anglers ever catch. Small but spirited.', basePrice: 2 },
  { name: 'Bream', scientificName: 'Abramis brama', weightMin: 0.3, weightMax: 4.0, fightRating: 2, habitat: 'lake', depthPreference: 'mid', biomes: ['plains', 'wetlands'], timePreference: 'dawn', weatherPreference: 'any', lurePreference: ['worm', 'corn', 'bread'], rarity: 'common', flavorText: 'A deep-bodied fish found in slow-moving waters across the lowlands.', basePrice: 5 },
  { name: 'Tench', scientificName: 'Tinca tinca', weightMin: 0.5, weightMax: 5.0, fightRating: 3, habitat: 'lake', depthPreference: 'deep', biomes: ['plains', 'wetlands', 'forest'], timePreference: 'dawn', weatherPreference: 'rain', lurePreference: ['worm', 'corn', 'bread'], rarity: 'common', flavorText: 'The doctor fish. Said to heal other fish with its slime.', basePrice: 8 },
  { name: 'Roach', scientificName: 'Rutilus rutilus', weightMin: 0.1, weightMax: 1.5, fightRating: 1, habitat: 'river', depthPreference: 'shallow', biomes: ['plains', 'forest', 'wetlands'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['bread', 'worm', 'maggot'], rarity: 'common', flavorText: 'A silvery shoal fish, common in most temperate waters.', basePrice: 3 },
  { name: 'Walleye', scientificName: 'Sander vitreus', weightMin: 0.5, weightMax: 6.0, fightRating: 4, habitat: 'lake', depthPreference: 'mid', biomes: ['plains', 'forest'], timePreference: 'dusk', weatherPreference: 'any', lurePreference: ['jig', 'minnow', 'crankbait'], rarity: 'common', flavorText: 'Named for its pearlescent eyes. Excellent table fare.', basePrice: 15 },
  { name: 'Crappie', scientificName: 'Pomoxis nigromaculatus', weightMin: 0.1, weightMax: 1.5, fightRating: 2, habitat: 'lake', depthPreference: 'shallow', biomes: ['plains', 'forest', 'wetlands'], timePreference: 'dawn', weatherPreference: 'clear', lurePreference: ['jig', 'minnow', 'spinner'], rarity: 'common', flavorText: 'Schooling panfish that provide fast action when you find them.', basePrice: 5 },

  // === UNCOMMON FRESHWATER ===
  { name: 'Muskie', scientificName: 'Esox masquinongy', weightMin: 3.0, weightMax: 25.0, fightRating: 9, habitat: 'lake', depthPreference: 'mid', biomes: ['forest', 'plains'], timePreference: 'dusk', weatherPreference: 'any', lurePreference: ['bucktail', 'crankbait', 'jerkbait'], rarity: 'uncommon', flavorText: 'The fish of ten thousand casts. Massive, elusive, and powerful.', basePrice: 35 },
  { name: 'Lake Trout', scientificName: 'Salvelinus namaycush', weightMin: 1.0, weightMax: 15.0, fightRating: 6, habitat: 'lake', depthPreference: 'deep', biomes: ['mountain', 'tundra'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['spoon', 'jig', 'minnow'], rarity: 'uncommon', flavorText: 'Dwells in the cold depths of mountain lakes.', basePrice: 20 },
  { name: 'Steelhead', scientificName: 'Oncorhynchus mykiss irideus', weightMin: 2.0, weightMax: 10.0, fightRating: 8, habitat: 'river', depthPreference: 'mid', biomes: ['mountain', 'forest'], timePreference: 'dawn', weatherPreference: 'rain', lurePreference: ['fly', 'spoon', 'spinner'], rarity: 'uncommon', flavorText: 'The sea-run rainbow trout. A legendary fighter on light tackle.', basePrice: 25 },
  { name: 'Brook Trout', scientificName: 'Salvelinus fontinalis', weightMin: 0.2, weightMax: 3.0, fightRating: 4, habitat: 'river', depthPreference: 'shallow', biomes: ['mountain', 'forest', 'tundra'], timePreference: 'dawn', weatherPreference: 'clear', lurePreference: ['fly', 'worm', 'spinner'], rarity: 'uncommon', flavorText: 'A gem of cold mountain streams, with vivid markings.', basePrice: 16 },
  { name: 'Zander', scientificName: 'Sander lucioperca', weightMin: 1.0, weightMax: 8.0, fightRating: 5, habitat: 'lake', depthPreference: 'deep', biomes: ['plains', 'forest'], timePreference: 'night', weatherPreference: 'any', lurePreference: ['jig', 'minnow', 'soft plastic'], rarity: 'uncommon', flavorText: 'A nocturnal predator with large, light-sensitive eyes.', basePrice: 18 },
  { name: 'Grayling', scientificName: 'Thymallus thymallus', weightMin: 0.3, weightMax: 2.0, fightRating: 3, habitat: 'river', depthPreference: 'shallow', biomes: ['mountain', 'tundra'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['fly', 'nymph', 'worm'], rarity: 'uncommon', flavorText: 'The lady of the stream. Smells faintly of thyme when freshly caught.', basePrice: 14 },
  { name: 'Tiger Trout', scientificName: 'Salmo trutta × Salvelinus fontinalis', weightMin: 0.5, weightMax: 4.0, fightRating: 6, habitat: 'lake', depthPreference: 'mid', biomes: ['mountain', 'forest'], timePreference: 'dusk', weatherPreference: 'any', lurePreference: ['spinner', 'fly', 'minnow'], rarity: 'uncommon', flavorText: 'A rare hybrid with striking tiger-like markings.', basePrice: 22 },
  { name: 'Paddlefish', scientificName: 'Polyodon spathula', weightMin: 5.0, weightMax: 30.0, fightRating: 6, habitat: 'river', depthPreference: 'deep', biomes: ['plains', 'wetlands'], timePreference: 'any', weatherPreference: 'rain', lurePreference: ['plankton', 'dough'], rarity: 'uncommon', flavorText: 'An ancient filter feeder with a distinctive paddle-shaped snout.', basePrice: 28 },
  { name: 'Bowfin', scientificName: 'Amia calva', weightMin: 1.0, weightMax: 6.0, fightRating: 7, habitat: 'swamp', depthPreference: 'shallow', biomes: ['wetlands'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['worm', 'crankbait', 'topwater'], rarity: 'uncommon', flavorText: 'A living fossil. One of the most primitive surviving fishes.', basePrice: 12 },
  { name: 'Gar', scientificName: 'Lepisosteus osseus', weightMin: 1.0, weightMax: 10.0, fightRating: 5, habitat: 'swamp', depthPreference: 'shallow', biomes: ['wetlands', 'plains'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['rope lure', 'minnow', 'topwater'], rarity: 'uncommon', flavorText: 'An armored predator whose lineage predates the dinosaurs.', basePrice: 10 },
  { name: 'Burbot', scientificName: 'Lota lota', weightMin: 0.5, weightMax: 8.0, fightRating: 3, habitat: 'lake', depthPreference: 'deep', biomes: ['tundra', 'mountain'], timePreference: 'night', weatherPreference: 'any', lurePreference: ['jig', 'minnow', 'glow lure'], rarity: 'uncommon', flavorText: 'The only freshwater cod. Thrives in icy northern waters.', basePrice: 12 },
  { name: 'Flathead Catfish', scientificName: 'Pylodictis olivaris', weightMin: 2.0, weightMax: 25.0, fightRating: 7, habitat: 'river', depthPreference: 'deep', biomes: ['plains', 'wetlands'], timePreference: 'night', weatherPreference: 'any', lurePreference: ['live bait', 'stinkbait', 'cut bait'], rarity: 'uncommon', flavorText: 'A massive bottom dweller that prefers live prey.', basePrice: 15 },
  { name: 'White Bass', scientificName: 'Morone chrysops', weightMin: 0.3, weightMax: 2.5, fightRating: 4, habitat: 'lake', depthPreference: 'mid', biomes: ['plains', 'forest'], timePreference: 'dawn', weatherPreference: 'any', lurePreference: ['spinner', 'jig', 'minnow'], rarity: 'uncommon', flavorText: 'Schooling predators that create feeding frenzies near the surface.', basePrice: 8 },
  { name: 'Freshwater Drum', scientificName: 'Aplodinotus grunniens', weightMin: 0.5, weightMax: 8.0, fightRating: 4, habitat: 'river', depthPreference: 'mid', biomes: ['plains', 'wetlands'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['worm', 'crayfish', 'jig'], rarity: 'uncommon', flavorText: 'Makes a distinct drumming sound. The only freshwater member of its family.', basePrice: 7 },

  // === RARE FRESHWATER ===
  { name: 'Sturgeon', scientificName: 'Acipenser fulvescens', weightMin: 10.0, weightMax: 80.0, fightRating: 9, habitat: 'river', depthPreference: 'deep', biomes: ['plains', 'mountain'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['worm', 'cut bait', 'crayfish'], rarity: 'rare', flavorText: 'An ancient giant that can live over a century. Handle with reverence.', basePrice: 60 },
  { name: 'Golden Trout', scientificName: 'Oncorhynchus aguabonita', weightMin: 0.2, weightMax: 2.5, fightRating: 4, habitat: 'river', depthPreference: 'shallow', biomes: ['mountain'], timePreference: 'dawn', weatherPreference: 'clear', lurePreference: ['fly', 'nymph', 'spinner'], rarity: 'rare', flavorText: 'A jewel of alpine streams. Found only at the highest elevations.', basePrice: 45 },
  { name: 'Albino Catfish', scientificName: 'Ictalurus punctatus var. albino', weightMin: 1.0, weightMax: 12.0, fightRating: 5, habitat: 'lake', depthPreference: 'deep', biomes: ['wetlands', 'plains'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['stinkbait', 'worm', 'chicken'], rarity: 'rare', flavorText: 'A ghostly white catfish. Extremely rare and considered a good omen.', basePrice: 50 },
  { name: 'Giant Pike', scientificName: 'Esox lucius giganteus', weightMin: 8.0, weightMax: 25.0, fightRating: 9, habitat: 'lake', depthPreference: 'mid', biomes: ['tundra', 'forest'], timePreference: 'dusk', weatherPreference: 'rain', lurePreference: ['jerkbait', 'spoon', 'live bait'], rarity: 'rare', flavorText: 'A monster pike that rules the deepest lake bays. Legends speak of its ferocity.', basePrice: 55 },
  { name: 'Blue Catfish', scientificName: 'Ictalurus furcatus', weightMin: 5.0, weightMax: 50.0, fightRating: 8, habitat: 'river', depthPreference: 'deep', biomes: ['plains', 'wetlands'], timePreference: 'night', weatherPreference: 'any', lurePreference: ['cut bait', 'live bait', 'stinkbait'], rarity: 'rare', flavorText: 'The largest catfish species. Can grow to truly impressive sizes.', basePrice: 40 },
  { name: 'Arctic Char', scientificName: 'Salvelinus alpinus', weightMin: 0.5, weightMax: 6.0, fightRating: 5, habitat: 'lake', depthPreference: 'deep', biomes: ['tundra'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['spoon', 'fly', 'spinner'], rarity: 'rare', flavorText: 'The northernmost freshwater fish. Brilliantly colored during spawning.', basePrice: 35 },
  { name: 'Marble Trout', scientificName: 'Salmo marmoratus', weightMin: 1.0, weightMax: 12.0, fightRating: 7, habitat: 'river', depthPreference: 'mid', biomes: ['mountain'], timePreference: 'dawn', weatherPreference: 'clear', lurePreference: ['fly', 'minnow', 'spinner'], rarity: 'rare', flavorText: 'Recognized by its distinctive marbled pattern. Found in pristine mountain rivers.', basePrice: 42 },
  { name: 'Snakehead', scientificName: 'Channa argus', weightMin: 1.0, weightMax: 8.0, fightRating: 7, habitat: 'swamp', depthPreference: 'shallow', biomes: ['wetlands'], timePreference: 'day', weatherPreference: 'rain', lurePreference: ['topwater', 'frog lure', 'minnow'], rarity: 'rare', flavorText: 'An air-breathing predator that can survive out of water for days.', basePrice: 30 },
  { name: 'Wels Catfish', scientificName: 'Silurus glanis', weightMin: 10.0, weightMax: 80.0, fightRating: 10, habitat: 'river', depthPreference: 'deep', biomes: ['plains', 'wetlands'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['live bait', 'cut bait', 'topwater'], rarity: 'rare', flavorText: 'The largest European freshwater fish. A true river monster.', basePrice: 55 },
  { name: 'Alligator Gar', scientificName: 'Atractosteus spatula', weightMin: 10.0, weightMax: 70.0, fightRating: 8, habitat: 'swamp', depthPreference: 'shallow', biomes: ['wetlands'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['rope lure', 'live bait', 'cut bait'], rarity: 'rare', flavorText: 'A prehistoric predator that looks like a cross between a fish and an alligator.', basePrice: 48 },

  // === TROPICAL / EXOTIC (invented) ===
  { name: 'Crimson Sunperch', scientificName: 'Helianthichthys rubrum', weightMin: 0.3, weightMax: 2.0, fightRating: 3, habitat: 'lake', depthPreference: 'shallow', biomes: ['desert', 'plains'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['fly', 'cricket', 'worm'], rarity: 'uncommon', flavorText: 'A brilliantly red sunfish found in warm desert oases.', basePrice: 16 },
  { name: 'Emerald Darter', scientificName: 'Viridiperca smaragdus', weightMin: 0.05, weightMax: 0.3, fightRating: 1, habitat: 'river', depthPreference: 'shallow', biomes: ['forest', 'wetlands'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['nymph', 'tiny jig'], rarity: 'uncommon', flavorText: 'A tiny jewel-toned fish that darts between river stones.', basePrice: 12 },
  { name: 'Thornback Rudd', scientificName: 'Spinorutilus acanthus', weightMin: 0.5, weightMax: 3.0, fightRating: 4, habitat: 'lake', depthPreference: 'mid', biomes: ['wetlands'], timePreference: 'dawn', weatherPreference: 'rain', lurePreference: ['bread', 'worm', 'corn'], rarity: 'uncommon', flavorText: 'Named for the sharp ridge of spines along its back.', basePrice: 11 },
  { name: 'Glasswater Minnow', scientificName: 'Transparens crystallus', weightMin: 0.01, weightMax: 0.1, fightRating: 1, habitat: 'river', depthPreference: 'shallow', biomes: ['mountain', 'forest'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['tiny jig', 'nymph'], rarity: 'common', flavorText: 'Nearly transparent. You can see its tiny heart beating through its skin.', basePrice: 3 },
  { name: 'Ironscale Carp', scientificName: 'Ferrocyprinus durus', weightMin: 3.0, weightMax: 20.0, fightRating: 7, habitat: 'lake', depthPreference: 'deep', biomes: ['mountain', 'plains'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['dough', 'corn', 'boilie'], rarity: 'uncommon', flavorText: 'Its scales are so thick they were once used as arrowheads.', basePrice: 14 },
  { name: 'Marsh Phantom', scientificName: 'Phantomichthys palustris', weightMin: 0.5, weightMax: 4.0, fightRating: 5, habitat: 'swamp', depthPreference: 'shallow', biomes: ['wetlands'], timePreference: 'night', weatherPreference: 'rain', lurePreference: ['glow lure', 'worm', 'frog lure'], rarity: 'rare', flavorText: 'A bioluminescent fish that glows faintly in swamp waters at night.', basePrice: 38 },

  // === DEEP WATER (advanced gear required) ===
  { name: 'Abyssal Cod', scientificName: 'Gadus profundus', weightMin: 2.0, weightMax: 15.0, fightRating: 5, habitat: 'lake', depthPreference: 'deep', biomes: ['tundra', 'mountain'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['deep jig', 'glow lure', 'cut bait'], rarity: 'uncommon', flavorText: 'Lives in the deepest parts of glacial lakes, rarely seeing light.', basePrice: 22 },
  { name: 'Deepmaw Eel', scientificName: 'Anguillichthys abyssalis', weightMin: 1.0, weightMax: 8.0, fightRating: 6, habitat: 'lake', depthPreference: 'deep', biomes: ['mountain', 'tundra'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['glow lure', 'live bait', 'cut bait'], rarity: 'rare', flavorText: 'An eel that dwells in underwater caves. Its jaws unhinge to swallow large prey.', basePrice: 40 },
  { name: 'Stone Lurker', scientificName: 'Lithoichthys immobilis', weightMin: 3.0, weightMax: 12.0, fightRating: 4, habitat: 'lake', depthPreference: 'deep', biomes: ['mountain'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['deep jig', 'worm', 'crayfish'], rarity: 'uncommon', flavorText: 'Perfectly camouflaged among lake-bottom stones. Ambushes passing prey.', basePrice: 18 },
  { name: 'Twilight Perch', scientificName: 'Perca crepusculus', weightMin: 0.5, weightMax: 3.0, fightRating: 3, habitat: 'lake', depthPreference: 'deep', biomes: ['forest', 'mountain'], timePreference: 'dusk', weatherPreference: 'any', lurePreference: ['jig', 'minnow', 'glow lure'], rarity: 'uncommon', flavorText: 'Rises from the depths only during twilight hours to feed.', basePrice: 15 },
  { name: 'Void Sturgeon', scientificName: 'Acipenser tenebris', weightMin: 15.0, weightMax: 100.0, fightRating: 10, habitat: 'lake', depthPreference: 'deep', biomes: ['mountain', 'tundra'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['deep jig', 'cut bait', 'crayfish'], rarity: 'rare', flavorText: 'A pitch-black sturgeon that inhabits the deepest lake trenches. Ancient beyond measure.', basePrice: 75 },

  // === LEGENDARY (one per major biome, massively oversized, named) ===
  { name: 'Old Whiskers', scientificName: 'Silurus legendarius', weightMin: 80.0, weightMax: 120.0, fightRating: 10, habitat: 'lake', depthPreference: 'deep', biomes: ['plains'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['legendary bait'], rarity: 'legendary', flavorText: 'The oldest catfish in the lowland lakes. Fishermen speak of it in hushed tones. Its whiskers are said to be longer than a man is tall.', basePrice: 500 },
  { name: 'The Silver King', scientificName: 'Salmo rex argenteus', weightMin: 20.0, weightMax: 40.0, fightRating: 10, habitat: 'river', depthPreference: 'mid', biomes: ['mountain'], timePreference: 'dawn', weatherPreference: 'clear', lurePreference: ['legendary bait', 'golden fly'], rarity: 'legendary', flavorText: 'A salmon of impossible size and brilliance. Said to appear only once per generation in the highest mountain rivers.', basePrice: 500 },
  { name: 'Mossjaw', scientificName: 'Esox titanicus', weightMin: 30.0, weightMax: 50.0, fightRating: 10, habitat: 'lake', depthPreference: 'shallow', biomes: ['forest'], timePreference: 'dusk', weatherPreference: 'rain', lurePreference: ['legendary bait', 'massive jerkbait'], rarity: 'legendary', flavorText: 'A pike so large that moss grows on its back. It has capsized small boats. The terror of the forest lakes.', basePrice: 500 },
  { name: 'The Pale Leviathan', scientificName: 'Acipenser albinus colossus', weightMin: 100.0, weightMax: 200.0, fightRating: 10, habitat: 'lake', depthPreference: 'deep', biomes: ['tundra'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['legendary bait'], rarity: 'legendary', flavorText: 'A white sturgeon of mythic proportions. Lives beneath the ice of the northernmost lakes. Few have seen it. Fewer still have hooked it.', basePrice: 500 },
  { name: 'Swamp Mother', scientificName: 'Channa matriarca', weightMin: 15.0, weightMax: 30.0, fightRating: 10, habitat: 'swamp', depthPreference: 'shallow', biomes: ['wetlands'], timePreference: 'night', weatherPreference: 'storm', lurePreference: ['legendary bait', 'frog lure'], rarity: 'legendary', flavorText: 'The queen of the swamp. She guards her territory with terrifying aggression. Local fishermen leave offerings at the water\'s edge.', basePrice: 500 },
  { name: 'Dustfin', scientificName: 'Xerichthys colossus', weightMin: 10.0, weightMax: 25.0, fightRating: 10, habitat: 'lake', depthPreference: 'deep', biomes: ['desert'], timePreference: 'night', weatherPreference: 'clear', lurePreference: ['legendary bait'], rarity: 'legendary', flavorText: 'A massive fish that survives in the few deep oasis pools of the desert. Its scales shimmer like gold dust.', basePrice: 500 },

  // Additional common/uncommon to reach 60+
  { name: 'Pumpkinseed', scientificName: 'Lepomis gibbosus', weightMin: 0.05, weightMax: 0.4, fightRating: 1, habitat: 'lake', depthPreference: 'shallow', biomes: ['plains', 'forest'], timePreference: 'day', weatherPreference: 'clear', lurePreference: ['worm', 'cricket', 'fly'], rarity: 'common', flavorText: 'A beautifully colored sunfish with an orange spot on its gill plate.', basePrice: 3 },
  { name: 'Rock Bass', scientificName: 'Ambloplites rupestris', weightMin: 0.1, weightMax: 0.8, fightRating: 2, habitat: 'river', depthPreference: 'shallow', biomes: ['forest', 'mountain'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['worm', 'jig', 'crayfish'], rarity: 'common', flavorText: 'A red-eyed panfish found near rocky stream bottoms.', basePrice: 4 },
  { name: 'White Perch', scientificName: 'Morone americana', weightMin: 0.2, weightMax: 1.5, fightRating: 2, habitat: 'lake', depthPreference: 'mid', biomes: ['plains', 'wetlands'], timePreference: 'dawn', weatherPreference: 'any', lurePreference: ['worm', 'minnow', 'jig'], rarity: 'common', flavorText: 'A silvery fish often found in brackish estuaries and lakes.', basePrice: 5 },
  { name: 'Chub', scientificName: 'Squalius cephalus', weightMin: 0.3, weightMax: 3.0, fightRating: 3, habitat: 'river', depthPreference: 'shallow', biomes: ['plains', 'forest'], timePreference: 'day', weatherPreference: 'any', lurePreference: ['bread', 'spinner', 'worm'], rarity: 'common', flavorText: 'A stocky river fish with a broad head. Wary but not particularly fussy.', basePrice: 4 },
  { name: 'Ruffe', scientificName: 'Gymnocephalus cernua', weightMin: 0.05, weightMax: 0.3, fightRating: 1, habitat: 'lake', depthPreference: 'mid', biomes: ['plains', 'tundra'], timePreference: 'any', weatherPreference: 'any', lurePreference: ['worm', 'maggot'], rarity: 'common', flavorText: 'A small, spiny-finned fish. Not much to look at but tenacious.', basePrice: 2 },
  { name: 'Ide', scientificName: 'Leuciscus idus', weightMin: 0.5, weightMax: 4.0, fightRating: 3, habitat: 'river', depthPreference: 'mid', biomes: ['plains', 'forest'], timePreference: 'dawn', weatherPreference: 'rain', lurePreference: ['bread', 'worm', 'spinner'], rarity: 'common', flavorText: 'A handsome golden-flanked fish prized by river anglers.', basePrice: 7 },
];

/**
 * Get a fish species by name.
 */
export function getFishByName(name) {
  return FISH_SPECIES.find(f => f.name === name) || null;
}

/**
 * Get all fish species that can appear in a given biome.
 */
export function getFishForBiome(biome) {
  return FISH_SPECIES.filter(f => f.biomes.includes(biome));
}

/**
 * Get all fish of a given rarity.
 */
export function getFishByRarity(rarity) {
  return FISH_SPECIES.filter(f => f.rarity === rarity);
}

/**
 * Get fish that match given conditions (biome, time, weather, depth, habitat).
 */
export function getEligibleFish(biome, timeOfDay, weather, depth, habitat) {
  return FISH_SPECIES.filter(f => {
    if (!f.biomes.includes(biome)) return false;
    if (f.habitat !== habitat && habitat !== 'any') return false;
    if (f.timePreference !== 'any' && f.timePreference !== timeOfDay) return false;
    if (f.weatherPreference !== 'any' && f.weatherPreference !== weather) return false;
    if (f.depthPreference !== depth && depth !== 'any') return false;
    return true;
  });
}
