/**
 * ObjectPlacer - Trees, rocks placement using InstancedMesh.
 * Imports: Three.js.
 * Exports: ObjectPlacer class.
 * 
 * Takes object placement data (arrays of {x, z, type, scale, rotation})
 * generated by ChunkWorker, and builds InstancedMesh instances.
 * Uses Poisson disk sampling (done in worker).
 * Returns collision cylinders for Player collision.
 * All geometries/materials created once and shared across chunks.
 */

import * as THREE from 'three';

// Shared geometries (created once, never disposed — shared across all chunks)
let _sharedGeoInitialized = false;
const TREE_TRUNK_GEO = { ref: null };
const TREE_CANOPY_CONE_GEO = { ref: null };
const TREE_CANOPY_SPHERE_GEO = { ref: null };
const ROCK_GEO = { ref: null };

// Shared materials
const TREE_TRUNK_MAT = { ref: null };
const ROCK_MAT = { ref: null };

// Biome canopy colors
const CANOPY_COLORS = {
  plains:   0x4a8f3c,
  forest:   0x2d6b1e,
  mountain: 0x3a6b3a,
  desert:   0x8b8b3a,
  wetlands: 0x3a7d4a,
  tundra:   0x5a7d5a,
};

function initSharedGeometry() {
  if (_sharedGeoInitialized) return;
  _sharedGeoInitialized = true;

  TREE_TRUNK_GEO.ref = new THREE.CylinderGeometry(0.15, 0.3, 1, 6);
  TREE_CANOPY_CONE_GEO.ref = new THREE.ConeGeometry(1, 2, 6);
  TREE_CANOPY_SPHERE_GEO.ref = new THREE.SphereGeometry(1, 6, 5);
  ROCK_GEO.ref = new THREE.IcosahedronGeometry(1, 0);

  TREE_TRUNK_MAT.ref = new THREE.MeshStandardMaterial({
    color: 0x5c3a1e,
    roughness: 0.9,
  });

  ROCK_MAT.ref = new THREE.MeshStandardMaterial({
    color: 0x808080,
    roughness: 0.85,
    flatShading: true,
  });
}

// Reusable matrix and vectors for instancing (no allocations in loops)
const _matrix = new THREE.Matrix4();
const _position = new THREE.Vector3();
const _quaternion = new THREE.Quaternion();
const _scale = new THREE.Vector3();
const _euler = new THREE.Euler();

export default class ObjectPlacer {
  /**
   * Build InstancedMesh groups for a chunk's objects.
   * @param {Array} treeData - [{x, z, height, trunkHeight, canopyRadius, canopyType, lean, colorVariance}]
   * @param {Array} rockData - [{x, z, scale, rotY}]
   * @param {string} biome
   * @param {function(number, number): number} getHeight - terrain height function
   * @returns {{ group: THREE.Group, colliders: Array, disposables: Array }}
   */
  static buildChunkObjects(treeData, rockData, biome, getHeight) {
    initSharedGeometry();

    const group = new THREE.Group();
    const colliders = [];
    const disposables = [];

    // --- TREES ---
    if (treeData && treeData.length > 0) {
      const treeCount = treeData.length;

      // Trunk instances
      const trunkMesh = new THREE.InstancedMesh(
        TREE_TRUNK_GEO.ref, TREE_TRUNK_MAT.ref, treeCount
      );
      trunkMesh.castShadow = true;
      trunkMesh.receiveShadow = true;

      // Canopy instances — one per canopy type
      const canopyColor = new THREE.Color(CANOPY_COLORS[biome] || 0x4a8f3c);
      const canopyMat = new THREE.MeshStandardMaterial({
        color: canopyColor,
        roughness: 0.8,
      });
      disposables.push(canopyMat);

      // Split canopy by type
      const coneTrees = [];
      const sphereTrees = [];
      for (let i = 0; i < treeCount; i++) {
        if (treeData[i].canopyType === 0) {
          coneTrees.push({ idx: i, data: treeData[i] });
        } else {
          sphereTrees.push({ idx: i, data: treeData[i] });
        }
      }

      let coneCanopyMesh = null;
      if (coneTrees.length > 0) {
        coneCanopyMesh = new THREE.InstancedMesh(
          TREE_CANOPY_CONE_GEO.ref, canopyMat, coneTrees.length
        );
        coneCanopyMesh.castShadow = true;
        coneCanopyMesh.receiveShadow = true;
      }

      let sphereCanopyMesh = null;
      if (sphereTrees.length > 0) {
        sphereCanopyMesh = new THREE.InstancedMesh(
          TREE_CANOPY_SPHERE_GEO.ref, canopyMat, sphereTrees.length
        );
        sphereCanopyMesh.castShadow = true;
        sphereCanopyMesh.receiveShadow = true;
      }

      // Set trunk matrices
      for (let i = 0; i < treeCount; i++) {
        const t = treeData[i];
        const groundY = getHeight(t.x, t.z);
        if (groundY < -0.5) continue; // Don't place trees underwater

        const trunkH = t.trunkHeight;
        _position.set(t.x, groundY + trunkH / 2, t.z);
        _euler.set(0, 0, t.lean * 0.14); // lean angle
        _quaternion.setFromEuler(_euler);
        _scale.set(t.trunkRadius / 0.3, trunkH, t.trunkRadius / 0.3);
        _matrix.compose(_position, _quaternion, _scale);
        trunkMesh.setMatrixAt(i, _matrix);

        // Collision cylinder
        colliders.push({
          x: t.x,
          z: t.z,
          radius: Math.max(t.trunkRadius, 0.3),
          heightMin: groundY,
          heightMax: groundY + trunkH + t.canopyRadius * 2,
        });
      }
      trunkMesh.instanceMatrix.needsUpdate = true;

      // Set cone canopy matrices
      if (coneCanopyMesh) {
        for (let ci = 0; ci < coneTrees.length; ci++) {
          const { data: t } = coneTrees[ci];
          const groundY = getHeight(t.x, t.z);
          if (groundY < -0.5) continue;
          const canopyY = groundY + t.trunkHeight + t.canopyRadius;
          _position.set(t.x, canopyY, t.z);
          _quaternion.identity();
          _scale.set(t.canopyRadius, t.canopyRadius * 1.5, t.canopyRadius);
          _matrix.compose(_position, _quaternion, _scale);
          coneCanopyMesh.setMatrixAt(ci, _matrix);
        }
        coneCanopyMesh.instanceMatrix.needsUpdate = true;
      }

      // Set sphere canopy matrices
      if (sphereCanopyMesh) {
        for (let si = 0; si < sphereTrees.length; si++) {
          const { data: t } = sphereTrees[si];
          const groundY = getHeight(t.x, t.z);
          if (groundY < -0.5) continue;
          const canopyY = groundY + t.trunkHeight + t.canopyRadius * 0.8;
          _position.set(t.x, canopyY, t.z);
          _quaternion.identity();
          _scale.set(t.canopyRadius, t.canopyRadius * 0.8, t.canopyRadius);
          _matrix.compose(_position, _quaternion, _scale);
          sphereCanopyMesh.setMatrixAt(si, _matrix);
        }
        sphereCanopyMesh.instanceMatrix.needsUpdate = true;
      }

      group.add(trunkMesh);
      if (coneCanopyMesh) group.add(coneCanopyMesh);
      if (sphereCanopyMesh) group.add(sphereCanopyMesh);
      // InstancedMesh doesn't own geometry (shared), but we track for removal
    }

    // --- ROCKS ---
    if (rockData && rockData.length > 0) {
      const rockCount = rockData.length;
      const rockMesh = new THREE.InstancedMesh(
        ROCK_GEO.ref, ROCK_MAT.ref, rockCount
      );
      rockMesh.castShadow = true;
      rockMesh.receiveShadow = true;

      for (let i = 0; i < rockCount; i++) {
        const r = rockData[i];
        const groundY = getHeight(r.x, r.z);
        _position.set(r.x, groundY + r.scale * 0.3, r.z);
        _euler.set(0, r.rotY, 0);
        _quaternion.setFromEuler(_euler);
        _scale.set(r.scale, r.scale * 0.7, r.scale);
        _matrix.compose(_position, _quaternion, _scale);
        rockMesh.setMatrixAt(i, _matrix);

        if (r.scale > 0.8) {
          colliders.push({
            x: r.x,
            z: r.z,
            radius: r.scale * 0.6,
            heightMin: groundY,
            heightMax: groundY + r.scale * 1.4,
          });
        }
      }
      rockMesh.instanceMatrix.needsUpdate = true;
      group.add(rockMesh);
    }

    return { group, colliders, disposables };
  }
}
